routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Route::get('/', 'UniversityController@index')->name('home');
Route::get('/universities-all', 'UniversityController@all')->name('universities');
Route::get('/university/detail/{university}', 'UniversityController@show')->name('detail');
Route::post('/university/add-favorite/{university}', 'UniversityController@addFavorite')->name('favorite');
Route::post('/university/remove-favorite/{university}', 'UniversityController@removeFavorite')->name('unfavorite');

// Blog
Route::get('/blog', 'UniversityBlogController@index')->name('blog');

// User
Route::get('/user', 'UserController@index')->name('user');
Route::put('/user/update', 'UserController@update')->name('user.update');


Route::group(['middleware' => 'admin'], function () {
    Route::get('/dashboard', function () {
        return view('backend.pages.dashboard');
    })->name('dashboard');

    Route::resource('universities', 'Admin\UniversityController');

    Route::resource('university-faculties', 'Admin\UniversityFacultyController');
    Route::get('university/{university}/university-faculties/create', 'Admin\UniversityFacultyController@create')->name('university-faculties.create');

    Route::resource('university-study-program', 'Admin\UniversityStudyProgramsController');
    Route::get('university-faculty/{universityFaculty}/university-study-program/create', 'Admin\UniversityStudyProgramsController@create')->name('university-study-program.create');

    // Route::resource('university-register-schedule', 'Admin\UniversityRegisterSchedulesController');

    Route::resource('university-register-snm', 'Admin\UniversityRegisterSnmController');
    Route::resource('university-register-sbm', 'Admin\UniversityRegisterSbmController');
    Route::resource('university-register-mandiri', 'Admin\UniversityRegisterMandiriController');

    Route::resource('university-blog', 'Admin\UniversityBlogController');
    Route::get('university/{university}/university-blog/create', 'Admin\UniversityBlogController@create')->name('university-blog.create');
});


require __DIR__ . '/auth.php';

app/Models/UniversityStudyPrograms.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UniversityStudyPrograms extends Model
{
    use HasFactory;

    protected $table = 'university_study_programs';

    protected $fillable = [
        'faculty_id',
        'name',
        'slug',
    ];

    public function faculty()
    {
        return $this->belongsTo(UniversityFaculty::class, 'faculty_id');
    }
}

app/Http/Controllers/Admin/UniversityStudyProgramsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\UniversityStudyPrograms;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\UniversityFaculty;
use Illuminate\Support\Str;

class UniversityStudyProgramsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($facultyId)
    {
        // Ambil data faculty berdasarkan id
        $faculty = UniversityFaculty::findOrFail($facultyId);

        return view('backend.pages.university-study-programs.create', [
            'faculties' => $faculty
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Create data
        $data = UniversityStudyPrograms::create([
            'faculty_id' => $request->faculty_id,
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ]);

        return redirect()->route('university-faculties.show', $request->faculty_id)->with('success', 'Program studi berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function show(UniversityStudyPrograms $universityStudyPrograms)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Get data
        $data = UniversityStudyPrograms::findOrFail($id);

        return view('backend.pages.university-study-programs.edit', [
            'studyProgram' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //  Update data
        $data = UniversityStudyPrograms::findOrFail($id);

        $data->update([
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ]);

        return redirect()->route('university-faculties.show', $data->faculty_id)->with('success', 'Program studi berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Delete data
        $data = UniversityStudyPrograms::findOrFail($id);

        $data->delete();

        return redirect()->route('university-faculties.show', $data->faculty_id)->with('success', 'Program studi berhasil dihapus');
    }
}

app/Http/Controllers/UniversityStudyProgramsController.php
<?php

namespace App\Http\Controllers;

use App\Models\UniversityStudyPrograms;
use Illuminate\Http\Request;

class UniversityStudyProgramsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function show(UniversityStudyPrograms $universityStudyPrograms)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function edit(UniversityStudyPrograms $universityStudyPrograms)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UniversityStudyPrograms $universityStudyPrograms)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UniversityStudyPrograms  $universityStudyPrograms
     * @return \Illuminate\Http\Response
     */
    public function destroy(UniversityStudyPrograms $universityStudyPrograms)
    {
        //
    }
}

resources/views/backend/pages/university-study-programs/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambahkan Data Fakultas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card card-Vertical card-default card-md mb-4 mt-30">
                    <div class="card-header">
                        <h6>Tambah Data Program Studi</h6>
                    </div>
                    <div class="card-body pb-md-30">
                        {{-- Message Error --}}
                        @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            {{-- Foreach Error --}}
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>{{ $error }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            @endforeach
                        @endif
                        <div class="Vertical-form">
                            <form action="{{ route('university-study-program.store') }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('POST')
                                <div class="row">
                                    <div class="col-12 col-md-12">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Fakultas</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" hidden name="faculty_id" value="{{ $faculties->id }}"
                                                placeholder="1">
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" readonly value="{{ $faculties->name }}" placeholder="1">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Nama Program
                                                Studi</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="name" value="{{ old('name') }}" name="name" required
                                                placeholder="Teknik Informatika">
                                        </div>
                                    </div>
                                </div>
                                <div class="layout-button mt-25">
                                    <a href="#" class="btn btn-default btn-squared btn-light px-20 ">Cancel</a>
                                    <button type="submit"
                                        class="btn btn-primary btn-default btn-squared px-30">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/university-study-programs/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambahkan Data Fakultas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card card-Vertical card-default card-md mb-4 mt-30">
                    <div class="card-header">
                        <h6>Edit Data Fakultas</h6>
                    </div>
                    <div class="card-body pb-md-30">
                        {{-- Message Error --}}
                        @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            {{-- Foreach Error --}}
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>{{ $error }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            @endforeach
                        @endif
                        <div class="Vertical-form">
                            <form action="{{ route('university-study-program.update', $studyProgram->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-12 col-md-12">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Fakultas</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" hidden name="faculty_id"
                                                value="{{ $studyProgram->faculty->id }}" placeholder="1">
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" readonly value="{{ $studyProgram->faculty->name }}"
                                                placeholder="1">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Name</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="name" value="{{ $studyProgram->name }}" name="name" required
                                                placeholder="Universitas Pamulang">
                                        </div>
                                    </div>
                                </div>
                                <div class="layout-button mt-25">
                                    <a href="#" class="btn btn-default btn-squared btn-light px-20 ">Cancel</a>
                                    <button type="submit"
                                        class="btn btn-primary btn-default btn-squared px-30">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection