routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Route::get('/', 'UniversityController@index')->name('home');
Route::get('/universities-all', 'UniversityController@all')->name('universities');
Route::get('/university/detail/{university}', 'UniversityController@show')->name('detail');
Route::post('/university/add-favorite/{university}', 'UniversityController@addFavorite')->name('favorite');
Route::post('/university/remove-favorite/{university}', 'UniversityController@removeFavorite')->name('unfavorite');

// Blog
Route::get('/blog', 'UniversityBlogController@index')->name('blog');

// User
Route::get('/user', 'UserController@index')->name('user');
Route::put('/user/update', 'UserController@update')->name('user.update');


Route::group(['middleware' => 'admin'], function () {
    Route::get('/dashboard', function () {
        return view('backend.pages.dashboard');
    })->name('dashboard');

    Route::resource('universities', 'Admin\UniversityController');

    Route::resource('university-faculties', 'Admin\UniversityFacultyController');
    Route::get('university/{university}/university-faculties/create', 'Admin\UniversityFacultyController@create')->name('university-faculties.create');

    Route::resource('university-study-program', 'Admin\UniversityStudyProgramsController');
    Route::get('university-faculty/{universityFaculty}/university-study-program/create', 'Admin\UniversityStudyProgramsController@create')->name('university-study-program.create');

    // Route::resource('university-register-schedule', 'Admin\UniversityRegisterSchedulesController');

    Route::resource('university-register-snm', 'Admin\UniversityRegisterSnmController');
    Route::resource('university-register-sbm', 'Admin\UniversityRegisterSbmController');
    Route::resource('university-register-mandiri', 'Admin\UniversityRegisterMandiriController');

    Route::resource('university-blog', 'Admin\UniversityBlogController');
    Route::get('university/{university}/university-blog/create', 'Admin\UniversityBlogController@create')->name('university-blog.create');
});


require __DIR__ . '/auth.php';

app/Models/UniversityBlog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UniversityBlog extends Model
{
    use HasFactory;

    protected $fillable = [
        'university_id',
        'title',
        'slug',
        'image',
        'isi',
    ];

    public function university()
    {
        return $this->belongsTo(University::class);
    }
}

app/Http/Controllers/Admin/UniversityBlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\UniversityBlog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\University;
use Illuminate\Support\Str;

class UniversityBlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($univId)
    {
        $data = University::where('id', $univId)->first();

        return view('backend.pages.university-blog.create', [
            'university' => $data
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate =  $request->validate([
            'university_id' => 'required',
            'title' => 'required',
            'isi' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg|max:2048'
        ]);

        // Jika ada file gambar yang diupload
        if ($request->hasFile('image')) {
            // Mengambil file yang diupload
            $file = $request->file('image');
            // Mengambil nama file
            $fileName = $file->getClientOriginalName();
            // Menyimpan gambar ke folder public/img
            $file->storeAs('public/backend/images/universities/blog/', $fileName);
        }

        // Menyimpan data ke dalam table university_blogs
        $universityBlog = new UniversityBlog();

        $universityBlog->university_id = $request->university_id;
        $universityBlog->title = $request->title;
        $universityBlog->slug = Str::slug($request->title);
        $universityBlog->isi = $request->isi;
        $universityBlog->image = $fileName;

        $universityBlog->save();

        return redirect()->route('universities.show', $request->university_id)->with('success', 'Blog berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function show(UniversityBlog $universityBlog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function edit(UniversityBlog $universityBlog)
    {
        $data = UniversityBlog::findOrFail($universityBlog->id);


        return view('backend.pages.university-blog.edit', [
            'blog' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UniversityBlog $universityBlog)
    {
        $validate =  $request->validate([
            'title' => 'required',
            'isi' => 'required',
            'image' => 'image|mimes:jpeg,png,jpg|max:2048'
        ]);

        // Jika ada file gambar yang diupload
        if ($request->hasFile('image')) {

            // Menghapus file yang lama
            unlink(storage_path('app/public/backend/images/universities/blog/' . $universityBlog->image));

            // Mengambil file yang diupload
            $file = $request->file('image');
            // Mengambil nama file
            $fileName = $file->getClientOriginalName();
            // Menyimpan gambar ke folder public/img
            $file->storeAs('public/backend/images/universities/blog/', $fileName);


            // Menyimpan data ke dalam table university_blogs
            $universityBlog->title = $request->title;
            $universityBlog->slug = Str::slug($request->title);
            $universityBlog->isi = $request->isi;
            $universityBlog->image = $fileName;

            $universityBlog->update();
        } else {
            // Menyimpan data ke dalam table university_blogs
            $universityBlog->title = $request->title;
            $universityBlog->slug = Str::slug($request->title);
            $universityBlog->isi = $request->isi;

            $universityBlog->update();
        }

        return redirect()->route('universities.show', $universityBlog->university_id)->with('success', 'Blog berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $universityBlog = UniversityBlog::findOrFail($id);

        // Hapus
        unlink(storage_path('app/public/backend/images/universities/blog/' . $universityBlog->image));

        $universityBlog->delete();

        return redirect()->route('universities.show', $universityBlog->university_id)->with('success', 'Blog berhasil dihapus');
    }
}

app/Http/Controllers/UniversityBlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\UniversityBlog;
use Illuminate\Http\Request;

class UniversityBlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Tampilkan data
        $data = UniversityBlog::paginate(10);

        return view('frontend.blog', [
            'universityBlogs' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function show(UniversityBlog $universityBlog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function edit(UniversityBlog $universityBlog)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UniversityBlog $universityBlog)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UniversityBlog  $universityBlog
     * @return \Illuminate\Http\Response
     */
    public function destroy(UniversityBlog $universityBlog)
    {
        //
    }
}

resources/views/backend/pages/university-blog/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambahkan Data Universitas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card card-Vertical card-default card-md mb-4 mt-30">
                    <div class="card-header">
                        <h6>Tambah Data Universitas</h6>
                    </div>
                    <div class="card-body pb-md-30">
                        {{-- Message Error --}}
                        @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            {{-- Foreach Error --}}
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>{{ $error }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            @endforeach
                        @endif
                        <div class="Vertical-form">
                            <form action="{{ route('university-blog.store') }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('POST')
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Judul</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="name" value="{{ old('title') }}" name="title" required
                                                placeholder="Cara Membuat Blog">

                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15" hidden
                                                value="{{ $university['id'] }}" name="university_id" required
                                                placeholder="Cara Membuat Blog">
                                        </div>

                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Isi</label>
                                            <textarea class="form-control" name="isi" required id="exampleFormControlTextarea1" rows="3"
                                                placeholder="Blog Adalah Sebuah Artikel Yang ....">{{ old('isi') }}</textarea>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Gambar</label>
                                            <div class="custom-file">
                                                <input class="form-control custom-file-input" name="image" required
                                                    type="file" id="customFile">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="layout-button mt-25">
                                    <a href="{{ route('universities.index') }}"
                                        class="btn btn-default btn-squared btn-light px-20 ">Cancel</a>
                                    <button type="submit"
                                        class="btn btn-primary btn-default btn-squared px-30">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/university-blog/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambahkan Data Universitas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card card-Vertical card-default card-md mb-4 mt-30">
                    <div class="card-header">
                        <h6>Tambah Data Universitas</h6>
                    </div>
                    <div class="card-body pb-md-30">
                        {{-- Message Error --}}
                        @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            {{-- Foreach Error --}}
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>{{ $error }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            @endforeach
                        @endif
                        <div class="Vertical-form">
                            <form action="{{ route('university-blog.update', $blog->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Judul</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="name" value="{{ $blog->title }}" name="title" required
                                                placeholder="Cara Membuat Blog">
                                        </div>

                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Isi</label>
                                            <textarea class="form-control" name="isi" required id="exampleFormControlTextarea1" rows="3"
                                                placeholder="Blog Adalah Sebuah Artikel Yang ....">{{ $blog->isi }}</textarea>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Gambar</label>
                                            <div class="custom-file">
                                                <input class="form-control custom-file-input" name="image" type="file"
                                                    id="customFile">
                                                <label class="custom-file-label" for="customFile">*kosongkan jika tidak
                                                    ingin diubah</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="layout-button mt-25">
                                    <a href="{{ route('universities.index') }}"
                                        class="btn btn-default btn-squared btn-light px-20 ">Cancel</a>
                                    <button type="submit"
                                        class="btn btn-primary btn-default btn-squared px-30">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection