routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Route::get('/', 'UniversityController@index')->name('home');
Route::get('/universities-all', 'UniversityController@all')->name('universities');
Route::get('/university/detail/{university}', 'UniversityController@show')->name('detail');
Route::post('/university/add-favorite/{university}', 'UniversityController@addFavorite')->name('favorite');
Route::post('/university/remove-favorite/{university}', 'UniversityController@removeFavorite')->name('unfavorite');

// Blog
Route::get('/blog', 'UniversityBlogController@index')->name('blog');

// User
Route::get('/user', 'UserController@index')->name('user');
Route::put('/user/update', 'UserController@update')->name('user.update');


Route::group(['middleware' => 'admin'], function () {
    Route::get('/dashboard', function () {
        return view('backend.pages.dashboard');
    })->name('dashboard');

    Route::resource('universities', 'Admin\UniversityController');

    Route::resource('university-faculties', 'Admin\UniversityFacultyController');
    Route::get('university/{university}/university-faculties/create', 'Admin\UniversityFacultyController@create')->name('university-faculties.create');

    Route::resource('university-study-program', 'Admin\UniversityStudyProgramsController');
    Route::get('university-faculty/{universityFaculty}/university-study-program/create', 'Admin\UniversityStudyProgramsController@create')->name('university-study-program.create');

    // Route::resource('university-register-schedule', 'Admin\UniversityRegisterSchedulesController');

    Route::resource('university-register-snm', 'Admin\UniversityRegisterSnmController');
    Route::resource('university-register-sbm', 'Admin\UniversityRegisterSbmController');
    Route::resource('university-register-mandiri', 'Admin\UniversityRegisterMandiriController');

    Route::resource('university-blog', 'Admin\UniversityBlogController');
    Route::get('university/{university}/university-blog/create', 'Admin\UniversityBlogController@create')->name('university-blog.create');
});


require __DIR__ . '/auth.php';

app/Models/UniversityFaculty.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UniversityFaculty extends Model
{
    use HasFactory;

    // Fillable
    protected $fillable = [
        'name',
        'slug',
        'university_id'
    ];

    // Relationship
    public function university()
    {
        return $this->belongsTo(University::class);
    }
}

app/Http/Controllers/Admin/UniversityFacultyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\University;
use App\Models\UniversityFaculty;
use App\Models\UniversityStudyPrograms;
use Illuminate\Support\Str;
use Illuminate\Http\Request;


class UniversityFacultyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($univId)
    {
        $university = University::findOrFail($univId);

        return view('backend.pages.university-faculties.create', compact('university'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // Create data
        $data = UniversityFaculty::create([
            'university_id' => $request->university_id,
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ]);

        return redirect()->route('universities.show', $request->university_id)->with('success', 'Fakultas berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function show(UniversityFaculty $universityFaculty)
    {
        $facultyId = $universityFaculty->id;

        $studyProgram = UniversityStudyPrograms::where('faculty_id', $facultyId)->get();

        return view('backend.pages.university-faculties.show', [
            'studyProgram' => $studyProgram,
            'facultyId' => $facultyId,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function edit(UniversityFaculty $universityFaculty)
    {
        $data = UniversityFaculty::findOrFail($universityFaculty->id);

        return view('backend.pages.university-faculties.edit', [
            'faculty' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UniversityFaculty $universityFaculty)
    {
        UniversityFaculty::where('id', $universityFaculty->id)->update([
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ]);

        return redirect()->route('universities.show', $universityFaculty->university_id)->with('success', 'Fakultas berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function destroy(UniversityFaculty $universityFaculty)
    {
        // Delete data
        $universityFaculty->delete();

        return redirect()->route('universities.show', $universityFaculty->university_id)->with('success', 'Fakultas berhasil dihapus');
    }
}

app/Http/Controllers/UniversityFacultyController.php
<?php

namespace App\Http\Controllers;

use App\Models\University;
use App\Models\UniversityFaculty;
use App\Models\UniversityStudyPrograms;
use Illuminate\Http\Request;

class UniversityFacultyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($univId)
    {
        $university = University::find($univId);

        return view('backend.pages.university-faculties.create', compact('university'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function show(UniversityFaculty $universityFaculty)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function edit(UniversityFaculty $universityFaculty)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UniversityFaculty $universityFaculty)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UniversityFaculty  $universityFaculty
     * @return \Illuminate\Http\Response
     */
    public function destroy(UniversityFaculty $universityFaculty)
    {
        //
    }
}

resources/views/backend/pages/university-faculties/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambahkan Data Fakultas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card card-Vertical card-default card-md mb-4 mt-30">
                    <div class="card-header">
                        <h6>Tambah Data Fakultas</h6>
                    </div>
                    <div class="card-body pb-md-30">
                        {{-- Message Error --}}
                        @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            {{-- Foreach Error --}}
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>{{ $error }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            @endforeach
                        @endif
                        <div class="Vertical-form">
                            <form action="{{ route('university-faculties.store') }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('POST')
                                <div class="row">
                                    <div class="col-12 col-md-12">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Universitas</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" hidden name="university_id" value="{{ $university->id }}"
                                                placeholder="1">
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" readonly value="{{ $university->name }}" placeholder="1">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Name</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="name" value="{{ old('name') }}" name="name" required
                                                placeholder="Universitas Pamulang">
                                        </div>
                                    </div>
                                </div>
                                <div class="layout-button mt-25">
                                    <a href="#" class="btn btn-default btn-squared btn-light px-20 ">Cancel</a>
                                    <button type="submit"
                                        class="btn btn-primary btn-default btn-squared px-30">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/university-faculties/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Tambahkan Data Fakultas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card card-Vertical card-default card-md mb-4 mt-30">
                    <div class="card-header">
                        <h6>Edit Data Fakultas</h6>
                    </div>
                    <div class="card-body pb-md-30">
                        {{-- Message Error --}}
                        @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            {{-- Foreach Error --}}
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>{{ $error }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            @endforeach
                        @endif
                        <div class="Vertical-form">
                            <form action="{{ route('university-faculties.update', $faculty->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-12 col-md-12">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput3"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Universitas</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" hidden name="university_id"
                                                value="{{ $faculty->university->id }}" placeholder="1">
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="text" readonly value="{{ $faculty->university->name }}"
                                                placeholder="1">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput"
                                                class="color-dark fs-14 fw-500 align-center mb-10">Name</label>
                                            <input type="text"
                                                class="form-control ih-medium ip-gray radius-xs b-light px-15"
                                                id="name" value="{{ $faculty->name }}" name="name" required
                                                placeholder="Universitas Pamulang">
                                        </div>
                                    </div>
                                </div>
                                <div class="layout-button mt-25">
                                    <a href="#" class="btn btn-default btn-squared btn-light px-20 ">Cancel</a>
                                    <button type="submit"
                                        class="btn btn-primary btn-default btn-squared px-30">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/university-faculties/show.blade.php
@extends('layouts.dashboard')

@section('title', 'Data Universitas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                {{-- Jika ada flash session message --}}
                @if (session()->has('success'))
                    <div class=" alert alert-success alert-dismissible fade show mt-5" role="alert">
                        <div class="alert-content">
                            <p>
                                {{ session()->get('success') }}
                            </p>
                            <button type="button" class="btn-close text-capitalize" data-bs-dismiss="alert" aria-label="Close">
                                <img src="{{ asset('backend/img/svg/x.svg') }}" alt="x" class="svg"
                                    aria-hidden="true">
                            </button>
                        </div>
                    </div>
                @endif
            </div>
            <div class="col-12 col-md-12 mb-30">
                <div class="card mt-30">
                    <div class="card-body">
                        <div class="support-ticket-system support-ticket-system--search">
                            <div class="breadcrumb-main m-0 breadcrumb-main--table justify-content-sm-between">
                                <div class="d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
                                    <div
                                        class="d-flex align-items-center ticket__title justify-content-center me-md-25 mb-md-0 mb-20">
                                        <h4 class="text-capitalize fw-500 breadcrumb-title">
                                            Data Program Studi
                                        </h4>
                                    </div>
                                </div>
                                <a class="btn btn-primary"
                                    href="{{ route('university-study-program.create', $facultyId) }}">
                                    Tambah Data
                                </a>
                            </div>
                            <div
                                class="support-form datatable-support-form d-flex justify-content-xxl-between justify-content-center align-items-center flex-wrap">
                                <div class="support-form__input">
                                </div>
                                <div class="support-form__search">
                                </div>
                            </div>
                            <div class="userDatatable userDatatable--ticket userDatatable--ticket--2 mt-1">
                                <div class="table-responsive">
                                    <table class="table mb-0 table-borderless">
                                        <thead>
                                            <tr class="userDatatable-header">
                                                <th>
                                                    <span class="userDatatable-title">no</span>
                                                </th>
                                                <th>
                                                    <span class="userDatatable-title">nama</span>
                                                </th>
                                                <th>
                                                    <span class="userDatatable-title">fakultas</span>
                                                </th>
                                                <th>
                                                    <span class="userDatatable-title float-end">action</span>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($studyProgram as $item)
                                                <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>{{ $item->name }}</td>
                                                    <td>{{ $item->faculty->name }}</td>
                                                    <td>
                                                        <ul class="orderDatatable_actions mb-0 d-flex flex-wrap">
                                                            <div class="dropdown dropdown-click">
                                                                <button class="btn-link border-0 bg-transparent p-0"
                                                                    data-bs-toggle="dropdown" aria-haspopup="true"
                                                                    aria-expanded="false">
                                                                    <img src="{{ asset('backend/img/svg/more-horizontal.svg') }}"
                                                                        alt="more-horizontal" class="svg" />
                                                                </button>
                                                                <div
                                                                    class="dropdown-default dropdown-bottomLeft dropdown-menu-right dropdown-menu--dynamic dropdown-menu">
                                                                    <a class="dropdown-item"
                                                                        href="{{ route('university-study-program.edit', $item->id) }}">Edit</a>
                                                                    <form id="formDelete"
                                                                        action="{{ route('university-study-program.destroy', $item->id) }}"
                                                                        method="POST">
                                                                        @csrf
                                                                        @method('DELETE')
                                                                        <button type="submit" class="dropdown-item">
                                                                            Hapus
                                                                        </button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </ul>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="d-flex justify-content-end pt-30">
                                    <nav class="dm-page">
                                        {{-- Pagination --}}
                                        {{-- {{ $universities->links() }} --}}
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    {{-- On click deleteData mengarahkan ke form --}}
    <script>
        function deleteData() {
            event.preventDefault();
            document.getElementById('formDelete').submit();
        }
    </script>
@endpush