routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Route::get('/', 'UniversityController@index')->name('home');
Route::get('/universities-all', 'UniversityController@all')->name('universities');
Route::get('/university/detail/{university}', 'UniversityController@show')->name('detail');
Route::post('/university/add-favorite/{university}', 'UniversityController@addFavorite')->name('favorite');
Route::post('/university/remove-favorite/{university}', 'UniversityController@removeFavorite')->name('unfavorite');

// Blog
Route::get('/blog', 'UniversityBlogController@index')->name('blog');

// User
Route::get('/user', 'UserController@index')->name('user');
Route::put('/user/update', 'UserController@update')->name('user.update');


Route::group(['middleware' => 'admin'], function () {
    Route::get('/dashboard', function () {
        return view('backend.pages.dashboard');
    })->name('dashboard');

    Route::resource('universities', 'Admin\UniversityController');

    Route::resource('university-faculties', 'Admin\UniversityFacultyController');
    Route::get('university/{university}/university-faculties/create', 'Admin\UniversityFacultyController@create')->name('university-faculties.create');

    Route::resource('university-study-program', 'Admin\UniversityStudyProgramsController');
    Route::get('university-faculty/{universityFaculty}/university-study-program/create', 'Admin\UniversityStudyProgramsController@create')->name('university-study-program.create');

    // Route::resource('university-register-schedule', 'Admin\UniversityRegisterSchedulesController');

    Route::resource('university-register-snm', 'Admin\UniversityRegisterSnmController');
    Route::resource('university-register-sbm', 'Admin\UniversityRegisterSbmController');
    Route::resource('university-register-mandiri', 'Admin\UniversityRegisterMandiriController');

    Route::resource('university-blog', 'Admin\UniversityBlogController');
    Route::get('university/{university}/university-blog/create', 'Admin\UniversityBlogController@create')->name('university-blog.create');
});


require __DIR__ . '/auth.php';

app/Models/University.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class University extends Model
{
    use HasFactory;

    // Fillable
    protected $fillable = [
        'name',
        'description',
        'slug',
        'village',
        'district',
        'city',
        'province',
        'address',
        'telephone',
        'email',
        'website',
        'logo',
        'status'
    ];

    // Relationship
    public function faculties()
    {
        return $this->hasMany(UniversityFaculty::class);
    }
}

app/Http/Controllers/Admin/UniversityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\University;
use App\Models\UniversityBlog;
use App\Models\UniversityFaculty;
use App\Models\UniversityFavorites;
use App\Models\UniversityRegisterMandiri;
use App\Models\UniversityRegisterSbm;
use App\Models\UniversityRegisterSnm;
use App\Models\UniversityStudyPrograms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class UniversityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = University::all();

        // Paginate data
        $data = University::paginate(10);


        return view('backend.pages.university.index', [
            'universities' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.university.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate
        $validate = $request->validate([
            'name' => 'required|unique:universities,name',
            'description' => 'required',
            'address' => 'required',
            'telephone' => 'required',
            'email' => 'required|email|unique:universities,email',
            'website' => 'required',
            'logo' => 'required|image|mimes:png,jpg,jpeg|max:2048'
        ]);

        // Jika ada file logo yang diupload 
        if ($request->hasFile('logo')) {
            $file = $request->file('logo');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs('public/images/universities', $filename);
            $data['logo'] = $filename;

            University::create([
                'name' => $request->name,
                'description' => $request->description,
                'slug' => Str::slug($request->name),
                'village' => $request->village,
                'district' => $request->district,
                'city' => $request->city,
                'province' => $request->province,
                'address' => $request->address,
                'telephone' => $request->telephone,
                'email' => $request->email,
                'website' => $request->website,
                'logo' => $filename,
                'status' => 'active'
            ]);
        }


        return redirect()->route('universities.index')->with('success', 'Data universitas berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Get data
        $data = University::findOrFail($id);

        $faculties = UniversityFaculty::where('university_id', $id)->get();

        // Get data university faculty
        $dataFaculty = $data->faculties()->paginate(10);

        $studyProgram = UniversityStudyPrograms::where('faculty_id', $id)->get();

        $univId = $data->id;

        $univSnm = UniversityRegisterSnm::where('university_id', $id)->get();

        // Jika $univSnm tidak ada
        if (!$univSnm) {
            $univSnm = null;
        }

        $univSbm = UniversityRegisterSbm::where('university_id', $id)->get();

        // Jika $univSbm tidak ada
        if (!$univSbm) {
            $univSbm = null;
        }

        $univMandiri = UniversityRegisterMandiri::where('university_id', $id)->get();

        // Jika $univMandiri tidak ada
        if (!$univMandiri) {
            $univMandiri = null;
        }

        $blog = UniversityBlog::where('university_id', $id)->get();

        return view('backend.pages.university.show', [
            'university' => $data,
            'faculties' => $faculties,
            'faculty' => $dataFaculty,
            'studyProgram' => $studyProgram,
            'univSnm' => $univSnm,
            'univSbm' => $univSbm,
            'univMandiri' => $univMandiri,
            'blog' => $blog,
            'univId' => $univId
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Get data
        $data = University::findOrFail($id);

        return view('backend.pages.university.edit', [
            'university' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate
        $validate = $request->validate([
            'name' => 'required|unique:universities,name,' . $id,
            'description' => 'required',
            'address' => 'required',
            'telephone' => 'required',
            'email' => 'required|email|unique:universities,email,' . $id,
            'website' => 'required',
            'logo' => 'image|mimes:png,jpg,jpeg|max:2048'
        ]);

        // Get data
        $data = University::findOrFail($id);

        // Jika ada file logo yang diupload
        if ($request->hasFile('logo')) {
            // Delete logo
            unlink(public_path('storage/images/universities/' . $data->logo));

            // Upload logo
            $file = $request->file('logo');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs('public/images/universities', $filename);
            $data['logo'] = $filename;
        }

        // Update data
        $data->update([
            'name' => $request->name,
            'description' => $request->description,
            'slug' => Str::slug($request->name),
            'village' => $request->village,
            'district' => $request->district,
            'city' => $request->city,
            'province' => $request->province,
            'address' => $request->address,
            'telephone' => $request->telephone,
            'email' => $request->email,
            'website' => $request->website,
            'status' => $request->status
        ]);

        return redirect()->route('universities.index')->with('success', 'Data universitas berhasil diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Delete data
        $data = University::findOrFail($id);

        // Delete logo
        $logo = $data->logo;

        // Delete data
        $data->delete();

        // Delete logo
        unlink(public_path('storage/images/universities/' . $logo));

        return redirect()->route('universities.index')->with('success', 'Data universitas berhasil dihapus');
    }
}

app/Http/Controllers/UniversityController.php
<?php

namespace App\Http\Controllers;

use App\Models\University;
use App\Models\UniversityBlog;
use App\Models\UniversityFaculty;
use App\Models\UniversityFavorites;
use App\Models\UniversityRegisterMandiri;
use App\Models\UniversityRegisterSbm;
use App\Models\UniversityRegisterSnm;
use App\Models\UniversityStudyPrograms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UniversityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Cek apakah ada query string
        if (request()->query('q')) {
            $q = request()->query('q');

            $data = University::where('name', 'LIKE', '%' . $q . '%')->paginate(10);
        } else {
            // Paginate data
            $data = University::paginate(10);
        }

        return view('frontend.index', [
            'universities' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\University  $university
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Get data
        $data = University::findOrFail($id);

        $faculties = UniversityFaculty::where('university_id', $id)->get();

        // Get data university faculty
        $dataFaculty = $data->faculties()->paginate(10);

        $studyProgram = UniversityStudyPrograms::where('faculty_id', $id)->get();

        $univId = $data->id;

        $univSnm = UniversityRegisterSnm::where('university_id', $id)->get();

        // Jika $univSnm tidak ada
        if (!$univSnm) {
            $univSnm = null;
        }

        $univSbm = UniversityRegisterSbm::where('university_id', $id)->get();

        // Jika $univSbm tidak ada
        if (!$univSbm) {
            $univSbm = null;
        }

        $univMandiri = UniversityRegisterMandiri::where('university_id', $id)->get();

        // Jika $univMandiri tidak ada
        if (!$univMandiri) {
            $univMandiri = null;
        }

        $blog = UniversityBlog::where('university_id', $id)->get();

        $favorite = UniversityFavorites::where('university_id', $id)->where('user_id', Auth::user()->id)->get();

        return view('frontend.detail', [
            'university' => $data,
            'faculties' => $faculties,
            'faculty' => $dataFaculty,
            'studyProgram' => $studyProgram,
            'univSnm' => $univSnm,
            'univSbm' => $univSbm,
            'univMandiri' => $univMandiri,
            'blog' => $blog,
            'favorite' => $favorite,
            'univId' => $univId
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\University  $university
     * @return \Illuminate\Http\Response
     */
    public function edit(University $university)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\University  $university
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, University $university)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\University  $university
     * @return \Illuminate\Http\Response
     */
    public function destroy(University $university)
    {
        //
    }

    public function all()
    {
        // Cek apakah ada query string
        // Paginate data
        $data = University::paginate(10);


        return view('frontend.all', [
            'universities' => $data
        ]);
    }

    public function addFavorite($id)
    {
        // Get user
        $user = Auth::user();

        // Cek apakah ada user dengan id tersebut di tabel favorite
        $cek = UniversityFavorites::where('user_id', $user->id)->where('university_id', $id)->first();

        // Jika ada
        if ($cek) {
            return redirect()->back()->with('error', 'Universitas sudah ada di favorit');
        } else {
            UniversityFavorites::create([
                'user_id' => $user->id,
                'university_id' => $id
            ]);

            return redirect()->back()->with('success', 'Universitas berhasil ditambahkan ke favorit');
        }

        return redirect()->back()->with('error', 'Terjadi kesalahan');
    }

    public function removeFavorite($id)
    {
        // Get user
        $user = Auth::user();

        // Cek apakah ada user dengan id tersebut di tabel favorite
        $cek = UniversityFavorites::where('user_id', $user->id)->where('university_id', $id)->first();

        // Jika ada
        if ($cek) {
            $cek->delete();

            return redirect()->back()->with('success', 'Universitas berhasil dihapus dari favorit');
        } else {
            return redirect()->back()->with('error', 'Universitas tidak ada di favorit');
        }

        return redirect()->back()->with('error', 'Terjadi kesalahan');
    }
}

resources/views/backend/pages/university/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Data Universitas')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                {{-- Jika ada flash session message --}}
                @if (session()->has('success'))
                    <div class=" alert alert-success alert-dismissible fade show " role="alert">
                        <div class="alert-content">
                            <p>
                                {{ session()->get('success') }}
                            </p>
                            <button type="button" class="btn-close text-capitalize" data-bs-dismiss="alert" aria-label="Close">
                                <img src="{{ asset('backend/img/svg/x.svg') }}" alt="x" class="svg"
                                    aria-hidden="true">
                            </button>
                        </div>
                    </div>
                @endif
            </div>
            <div class="col-lg-12 mb-30">
                <div class="card mt-30">
                    <div class="card-body">
                        <div class="support-ticket-system support-ticket-system--search">
                            <div class="breadcrumb-main m-0 breadcrumb-main--table justify-content-sm-between">
                                <div class="d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
                                    <div
                                        class="d-flex align-items-center ticket__title justify-content-center me-md-25 mb-md-0 mb-20">
                                        <h4 class="text-capitalize fw-500 breadcrumb-title">
                                            Data Universitas
                                        </h4>
                                    </div>
                                </div>
                                {{-- <div class="action-btn"> --}}
                                <a class="btn btn-primary" href="{{ route('universities.create') }}">
                                    Tambah Data
                                </a>
                                {{-- </div> --}}
                            </div>
                            <div
                                class="support-form datatable-support-form d-flex justify-content-xxl-between justify-content-center align-items-center flex-wrap">
                                <div class="support-form__input">
                                </div>
                                <div class="support-form__search">
                                </div>
                            </div>
                            <div class="userDatatable userDatatable--ticket userDatatable--ticket--2 mt-1">
                                <div class="table-responsive">
                                    <table class="table mb-0 table-borderless">
                                        <thead>
                                            <tr class="userDatatable-header">
                                                <th>
                                                    <span class="userDatatable-title">no</span>
                                                </th>
                                                <th>
                                                    <span class="userDatatable-title">logo</span>
                                                </th>
                                                <th data-type="html" data-name="name">
                                                    <span class="userDatatable-title">nama</span>
                                                </th>
                                                <th data-type="html" data-name="village">
                                                    <span class="userDatatable-title">kelurahan</span>
                                                </th>
                                                <th data-type="html" data-name='district'>
                                                    <span class="userDatatable-title">kecamatan</span>
                                                </th>
                                                <th data-type="html" data-name='city'>
                                                    <span class="userDatatable-title">kabupaten</span>
                                                </th>
                                                <th data-type="html" data-name='province'>
                                                    <span class="userDatatable-title">provinsi</span>
                                                </th>
                                                <th data-type="html" data-name="address">
                                                    <span class="userDatatable-title">alamat</span>
                                                </th>
                                                <th data-type="html" data-name='telephone'>
                                                    <span class="userDatatable-title">telepon</span>
                                                </th>
                                                <th data-type="html" data-name='email'>
                                                    <span class="userDatatable-title">email</span>
                                                </th>
                                                <th data-type="html" data-name='website'>
                                                    <span class="userDatatable-title">website</span>
                                                </th>
                                                <th data-type="html" data-name="status">
                                                    <span class="userDatatable-title">status</span>
                                                </th>
                                                <th>
                                                    <span class="userDatatable-title float-end">action</span>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach ($universities as $university)
                                                <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>
                                                        <img src="{{ asset('storage/images/universities/' . $university->logo) }}"
                                                            alt="{{ $university->nama }}" width="100">
                                                    </td>
                                                    <td>{{ $university->name }}</td>
                                                    <td>{{ $university->village }}</td>
                                                    <td>{{ $university->district }}</td>
                                                    <td>{{ $university->city }}</td>
                                                    <td>{{ $university->province }}</td>
                                                    <td>{{ $university->address }}</td>
                                                    <td>{{ $university->telephone }}</td>
                                                    <td>{{ $university->email }}</td>
                                                    <td>{{ $university->website }}</td>
                                                    <td>
                                                        <div class="userDatatable-content d-inline-block">
                                                            @if ($university->status == 'active')
                                                                <span
                                                                    class="bg-opacity-success  color-success userDatatable-content-status active">Active</span>
                                                            @else
                                                                <span
                                                                    class="bg-opacity-danger color-danger userDatatable-content-status active">Inactive</span>
                                                            @endif
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <ul class="orderDatatable_actions mb-0 d-flex flex-wrap">
                                                            <div class="dropdown dropdown-click">
                                                                <button class="btn-link border-0 bg-transparent p-0"
                                                                    data-bs-toggle="dropdown" aria-haspopup="true"
                                                                    aria-expanded="false">
                                                                    <img src="{{ asset('backend/img/svg/more-horizontal.svg') }}"
                                                                        alt="more-horizontal" class="svg" />
                                                                </button>

                                                                <div
                                                                    class="dropdown-default dropdown-bottomLeft dropdown-menu-right dropdown-menu--dynamic dropdown-menu">
                                                                    <a class="dropdown-item"
                                                                        href="{{ route('universities.show', $university->id) }}">Detail</a>
                                                                    <a class="dropdown-item"
                                                                        href="{{ route('universities.edit', $university->id) }}">Edit</a>
                                                                    <form id="formDelete"
                                                                        action="{{ route('universities.destroy', $university->id) }}"
                                                                        method="POST">
                                                                        @csrf
                                                                        @method('DELETE')
                                                                        <button type="submit" class="dropdown-item">
                                                                            Hapus
                                                                        </button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </ul>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="d-flex justify-content-end pt-30">
                                    <nav class="dm-page">
                                        {{-- Pagination --}}
                                        {{ $universities->links() }}
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    {{-- On click deleteData mengarahkan ke form --}}
    <script>
        function deleteData() {
            event.preventDefault();
            document.getElementById('formDelete').submit();
        }
    </script>
@endpush